name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install

      # Ejecutar ESLint para revisar la calidad del código
      - name: Run ESLint
        run: npm run lint

      # Ejecutar las pruebas con Jest
      - name: Run tests
        run: npm test
